# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 06:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('YAAS_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pid',
            name='pidder',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
