# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-04 17:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('YAAS_App', '0002_auto_20171004_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction_endtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 10, 4, 17, 59, 37, 110613, tzinfo=utc)),
        ),
    ]
