# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YAAS_App', '0002_pid_pidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='latest_pid',
            field=models.DecimalField(decimal_places=2, max_digits=6),
            preserve_default=False,
        ),
    ]
