# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-04 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YAAS_App', '0004_auto_20171004_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='endtime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='auction',
            name='start_price',
            field=models.FloatField(default=0.0),
        ),
    ]
