# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-05 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YAAS_App', '0005_auto_20171004_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='start_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
