# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-14 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YAAS_App', '0007_auto_20171014_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction_status',
            field=models.CharField(choices=[('A', 'Active'), ('B', 'Banned'), ('D', 'Due'), ('E', 'Adjudicated')], max_length=1),
        ),
    ]
