# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-19 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YAAS_App', '0010_auto_20171019_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='lockedby',
            field=models.TextField(default=''),
        ),
    ]
