# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 07:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('YAAS_App', '0011_auction_lockedby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bid_datetime', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pid',
            name='auction_id',
        ),
        migrations.RemoveField(
            model_name='pid',
            name='pidder',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='latest_pid',
            new_name='latest_bid',
        ),
        migrations.DeleteModel(
            name='Pid',
        ),
        migrations.AddField(
            model_name='bid',
            name='auction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YAAS_App.Auction'),
        ),
        migrations.AddField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
