# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 16:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('YAAS_App', '0012_auto_20180428_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLanguageSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_preference', models.CharField(choices=[('de', 'German'), ('en', 'English'), ('fr', 'France')], max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
