# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YAAS_App', '0013_userlanguageselection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlanguageselection',
            name='lang_preference',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English'), ('fr', 'France')], default='en', max_length=4),
        ),
    ]
