# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-29 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YAAS_App', '0017_auto_20180429_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='lockedby',
            field=models.TextField(default='#'),
        ),
    ]
