# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-30 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YAAS_App', '0018_auto_20180429_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
